from modules.setup import Setup
from modules.wbs_framework import WbsFramework
from modules.schedule_framework import ScheduleFramework
from modules.legends_framework import LegendsFramework
from modules.post_processing_framework import PostProcessingFramework  
from modules.analytics_framework import AnalyticsFramework
