INSERT INTO auth_schema.users 
(version_id, status_id, role_id, name, middle_name, last_name, birth_date, email, profession)
VALUES
(1, 1, 1, 'Jason', 'William', 'Schroder', '', 'jasons@elevateconstructionist.com', 'Chief Operating Officer', 8),
(1, 1, 1, 'Katie', 'Michelle', 'Schroder', '', 'katies@elevateconstructionist.com', 'Chief Executive Officer', 8),
(1, 1, 1, 'Kevin', '', 'Rice', '', 'kevinr@elevateconstructionist.com', 'Chief Visionary Officer', 8),
(1, 1, 1, 'Samuel', '', 'Sandoval Miranda', '', 'samuels@elevateconstructionist.com', 'Chief of Staff', 8),
(1, 1, 1, 'Nicolas', '', 'Martínez Osorio', '', 'nicolasm@elevateconstructionist.com', 'Field Engineer', 8),
(1, 1, 1, 'Emilio', '', 'Robles Villanueva', '', 'emilior@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Ana', 'Luisa', 'Pérez Mayorquín', '', 'analuisam@elevateconstructionist.com', 'Director, Senior Project Manager', 8),
(1, 1, 1, 'Karol', 'Elizabeth', 'Zamora Ruiz', '', 'karolz@elevateconstructionist.com', 'Director of Operations', 8),
(1, 1, 1, 'Jesús', 'Martín', 'Camacho Gastelum', '', 'jesusc@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Daniel', '', 'Vásquez Fuentes', '', 'danielv@elevateconstructionist.com', 'Director of Innovation', 8),
(1, 1, 1, 'Lucía', 'Scarlett', 'Armenta Medina', '', 'luciam@elevateconstructionist.com', 'Project Manager 2', 8),
(1, 1, 1, 'Genaro', 'Kiyoshi', 'García Bautista', '', 'kiyoshig@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Ricardo', '', 'Lozano Perea', '', 'ricardol@elevateconstructionist.com', 'Project Director', 8),
(1, 1, 1, 'Rubí', 'Alejandra', 'Larios González', '', 'rubil@elevateconstructionist.com', 'People Development Specialist 2', 8),
(1, 1, 1, 'Io', 'Liliana', 'Uribe Casillas', '', 'lilianau@elevateconstructionist.com', 'Project Manager 2', 8),
(1, 1, 1, 'Neftalí', '', 'Ramírez Hernández', '', 'neftalir@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Samantha', 'Andrea', 'Pérez Pineda', '', 'samanthap@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Luis', 'Francisco', 'Valencia Figueroa', '', 'luisv@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Oscar', 'Edigar', 'Barreto Pérez', '', 'edigarb@elevateconstructionist.com', 'Project Director', 8),
(1, 1, 1, 'Diego', 'Benjamín', 'García Celaya', '', 'benjaming@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Alejandro', '', 'Peñuelas Castro', '', 'alejandrop@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Ricardo', '', 'Montes López de Lara', '', 'rmontes@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Marzén', 'Jimena', 'Molina García', '', 'marzenm@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'José', 'Eduardo', 'Rodriguez Martínez', '', 'eduardor@elevateconstructionist.com', 'Lead VDC Engineer', 8),
(1, 1, 1, 'Alondra', '', 'Barrios Tovar', '', 'alondrat@elevateconstructionist.com', 'Operations Lead', 8),
(1, 1, 1, 'Ximena', 'Zobeida', 'Jiménez Ayón', '', 'ximenaj@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Daniela', '', 'Jiménez Díaz', '', 'danielaj@elevateconstructionist.com', 'Sales and Marketing Manager', 8),
(1, 1, 1, 'Alfredo', 'Jafet', 'Mejia Paz', '1998-12-09', 'alfredom@elevateconstructionist.com', 'Software Engineer'),
(1, 1, 1, 'Yeénitza', 'Mariana', 'Montoya Rodríguez', '', 'yeenitzam@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'José', 'Andrés', 'Rodríguez Martínez', '', 'andresr@elevateconstructionist.com', 'Lead VDC Engineer', 8),
(1, 1, 1, 'Citlalli', 'Montserrat', 'Pérez Pulido', '', 'montsep@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Sherlyn', 'Itzel', 'Cuevas González', '', 'sherc@elevateconstructionist.com', 'Lead Lean Engineer', 8),
(1, 1, 1, 'Julieta', '', 'Mercado Camposllera', '', 'julietam@elevateconstructionist.com', 'Lead Lean Engineer', 8),
(1, 1, 1, 'Jimena', '', 'Alba Pérez', '', 'jimenap@elevateconstructionist.com', 'Project Manager', 8),
(1, 1, 1, 'Tanya', 'Montserrat', 'Pérez Navarro', '', 'tanyap@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Emilio', '', 'Rosell Gallego', '', 'emiliog@elevateconstructionist.com', 'Lead Lean Engineer', 8),
(1, 1, 1, 'María', 'Celeste', 'Sierra Martínez', '', 'celestes@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'José', 'Fernando', 'Rodríguez López', '', 'peper@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Aida', 'Airy', 'Pacheco Peña', '', 'airyp@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Fernando', '', 'Gamboa Morales', '', 'fernandog@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Ruth', '', 'Avila Eraña', '', 'ruthav@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Melissa', '', 'Gusi Brito', '', 'melissag@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Jesús', 'Uriel', 'Mora Arce', '', 'jmora@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Abril', 'Guadalupe', 'Armenta Medina', '', 'abrilm@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Héctor', 'Manuel', 'Beltrán Navarro', '', 'hectorb@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Ana', 'Lucía', 'Guzmán Fernández', '', 'aguzman@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Itzel', '', 'Alcantar Mendoza', '', 'itzelal@elevateconstructionist.com', 'Lean Engineer', 8),
(1, 1, 1, 'Edgar', '', 'Díaz Ruíz', '', 'ediaz@elevateconstructionist.com', 'Lean Engineer', 8);
